apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jarvis-rolebinding
  namespace: default
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: jarvis-svc-acct
  namespace: default
